args:
  - --v=2
  - --cloud-provider=aws
  - --cluster-name=8team-cluster

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
