# 베이스 이미지
FROM confluentinc/cp-kafka-connect:7.5.0

# 루트 권한으로 필요한 도구 설치 및 폴더 준비
USER root

# RedHat 계열 패키지 설치 및 설치 경로 강제 생성/권한 부여
RUN microdnf update && \
    microdnf install -y unzip && \
    microdnf clean all && \
    # 설치 폴더를 미리 만들고 appuser에게 소유권을 넘김
    mkdir -p /usr/share/confluent-hub-components && \
    chown -R appuser:appuser /usr/share/confluent-hub-components /etc/kafka-connect/jars

# 다시 일반 사용자(appuser)로 전환
USER appuser

# 커넥터 설치
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-azure-blob-storage:2.5.3 && \
    confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.5.0

# 실행 명령
CMD ["/etc/confluent/docker/run"]